import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

List<String> wordsForLevel(String level) {
// Banco de palabras DEPURADO para Draw & Guess (local).
// Es el MISMO banco que siembra seed_words_v3.py en Firestore (online),
// para que el juego local y el online usen exactamente las mismas palabras.
// Totales: facil 868 | medio 588 | dificil 315  (= 1771)
//
// Argumento  : level (String) -> 'facil' | 'medio' | 'dificil'
// Return Type: String  ("Is List" = ON)   ->  List<String>
  List<String> wordsForLevel(String level) {
    const List<String> facil = [
      'gato',
      'perro',
      'pez',
      'pájaro',
      'ratón',
      'vaca',
      'caballo',
      'cerdo',
      'oveja',
      'pato',
      'gallina',
      'conejo',
      'león',
      'tigre',
      'elefante',
      'mono',
      'oso',
      'jirafa',
      'cebra',
      'hipopótamo',
      'rinoceronte',
      'camello',
      'canguro',
      'koala',
      'panda',
      'lobo',
      'zorro',
      'ardilla',
      'erizo',
      'tortuga',
      'rana',
      'serpiente',
      'cocodrilo',
      'lagarto',
      'caracol',
      'araña',
      'abeja',
      'mariposa',
      'hormiga',
      'mosca',
      'gusano',
      'oruga',
      'pulpo',
      'cangrejo',
      'delfín',
      'ballena',
      'tiburón',
      'foca',
      'pingüino',
      'loro',
      'búho',
      'águila',
      'paloma',
      'cisne',
      'pavo',
      'gallo',
      'pollito',
      'cabra',
      'burro',
      'toro',
      'murciélago',
      'caballito',
      'manzana',
      'pera',
      'plátano',
      'naranja',
      'limón',
      'fresa',
      'cereza',
      'uva',
      'sandía',
      'melón',
      'piña',
      'kiwi',
      'mango',
      'coco',
      'melocotón',
      'ciruela',
      'mandarina',
      'granada',
      'tomate',
      'zanahoria',
      'patata',
      'cebolla',
      'pimiento',
      'lechuga',
      'pepino',
      'calabaza',
      'maíz',
      'brócoli',
      'champiñón',
      'ajo',
      'guisante',
      'aceituna',
      'berenjena',
      'rábano',
      'pan',
      'queso',
      'huevo',
      'leche',
      'mantequilla',
      'pizza',
      'hamburguesa',
      'perrito',
      'sándwich',
      'taco',
      'tostada',
      'galleta',
      'pastel',
      'tarta',
      'helado',
      'chocolate',
      'caramelo',
      'piruleta',
      'donut',
      'cruasán',
      'magdalena',
      'bocadillo',
      'sopa',
      'ensalada',
      'arroz',
      'pasta',
      'espagueti',
      'salchicha',
      'flan',
      'yogur',
      'miel',
      'mermelada',
      'palomitas',
      'patatas',
      'café',
      'té',
      'zumo',
      'agua',
      'refresco',
      'batido',
      'limonada',
      'silla',
      'mesa',
      'cama',
      'sofá',
      'sillón',
      'lámpara',
      'reloj',
      'espejo',
      'cuadro',
      'estantería',
      'armario',
      'cajón',
      'puerta',
      'ventana',
      'llave',
      'candado',
      'escoba',
      'cubo',
      'fregona',
      'plancha',
      'aspiradora',
      'televisión',
      'radio',
      'teléfono',
      'ordenador',
      'teclado',
      'pantalla',
      'altavoz',
      'auriculares',
      'cámara',
      'bombilla',
      'enchufe',
      'pila',
      'linterna',
      'vela',
      'cerilla',
      'mechero',
      'alfombra',
      'cortina',
      'almohada',
      'manta',
      'percha',
      'paraguas',
      'abanico',
      'despertador',
      'calendario',
      'tenedor',
      'cuchillo',
      'cuchara',
      'plato',
      'vaso',
      'taza',
      'jarra',
      'sartén',
      'olla',
      'cazo',
      'colador',
      'rodillo',
      'batidora',
      'tostadora',
      'tetera',
      'cafetera',
      'nevera',
      'horno',
      'microondas',
      'lavadora',
      'grifo',
      'ducha',
      'bañera',
      'inodoro',
      'lavabo',
      'jabón',
      'champú',
      'toalla',
      'peine',
      'secador',
      'tijeras',
      'esponja',
      'cepillo',
      'camiseta',
      'pantalón',
      'vestido',
      'falda',
      'abrigo',
      'chaqueta',
      'jersey',
      'sudadera',
      'camisa',
      'corbata',
      'cinturón',
      'calcetines',
      'zapatos',
      'zapatillas',
      'botas',
      'sandalias',
      'chanclas',
      'gorra',
      'sombrero',
      'bufanda',
      'guantes',
      'gafas',
      'anillo',
      'collar',
      'pendientes',
      'pulsera',
      'mochila',
      'bolso',
      'cartera',
      'bañador',
      'pijama',
      'delantal',
      'casco',
      'bikini',
      'gorro',
      'cabeza',
      'cara',
      'ojo',
      'oreja',
      'nariz',
      'boca',
      'diente',
      'lengua',
      'labio',
      'ceja',
      'pestaña',
      'pelo',
      'cuello',
      'hombro',
      'brazo',
      'codo',
      'mano',
      'dedo',
      'uña',
      'pierna',
      'rodilla',
      'pie',
      'talón',
      'barriga',
      'espalda',
      'corazón',
      'cerebro',
      'hueso',
      'esqueleto',
      'sol',
      'luna',
      'estrella',
      'nube',
      'lluvia',
      'nieve',
      'rayo',
      'arcoíris',
      'viento',
      'fuego',
      'gota',
      'montaña',
      'volcán',
      'río',
      'lago',
      'mar',
      'playa',
      'isla',
      'desierto',
      'bosque',
      'árbol',
      'flor',
      'hoja',
      'rama',
      'raíz',
      'tronco',
      'césped',
      'hierba',
      'roca',
      'piedra',
      'arena',
      'concha',
      'cactus',
      'seta',
      'pino',
      'palmera',
      'girasol',
      'rosa',
      'tulipán',
      'margarita',
      'hongo',
      'coche',
      'moto',
      'bicicleta',
      'camión',
      'autobús',
      'tren',
      'avión',
      'barco',
      'helicóptero',
      'cohete',
      'globo',
      'patinete',
      'monopatín',
      'triciclo',
      'tractor',
      'grúa',
      'ambulancia',
      'taxi',
      'furgoneta',
      'caravana',
      'submarino',
      'canoa',
      'velero',
      'pelota',
      'cometa',
      'yoyó',
      'peonza',
      'canica',
      'muñeca',
      'peluche',
      'robot',
      'tambor',
      'trompeta',
      'guitarra',
      'piano',
      'flauta',
      'maracas',
      'pandereta',
      'dado',
      'carta',
      'puzle',
      'tobogán',
      'columpio',
      'balancín',
      'globos',
      'lápiz',
      'bolígrafo',
      'goma',
      'sacapuntas',
      'regla',
      'cuaderno',
      'libro',
      'pincel',
      'pintura',
      'rotulador',
      'pegamento',
      'grapadora',
      'clip',
      'carpeta',
      'folio',
      'libreta',
      'mapa',
      'pizarra',
      'tiza',
      'calculadora',
      'círculo',
      'cuadrado',
      'triángulo',
      'rectángulo',
      'rombo',
      'óvalo',
      'flecha',
      'cruz',
      'espiral',
      'punto',
      'línea',
      'casa',
      'tienda',
      'escuela',
      'iglesia',
      'castillo',
      'faro',
      'puente',
      'torre',
      'cabaña',
      'iglú',
      'granja',
      'establo',
      'molino',
      'hospital',
      'bandera',
      'corona',
      'espada',
      'escudo',
      'cofre',
      'brújula',
      'ancla',
      'pala',
      'rastrillo',
      'regadera',
      'maceta',
      'manguera',
      'martillo',
      'destornillador',
      'sierra',
      'clavo',
      'tornillo',
      'llave inglesa',
      'metro',
      'sombrilla',
      'hamaca',
      'flotador',
      'reloj de arena',
      'hámster',
      'conejillo de indias',
      'potro',
      'ternero',
      'cordero',
      'lechón',
      'gatito',
      'cachorro',
      'renacuajo',
      'sapo',
      'salamandra',
      'gecko',
      'iguana verde',
      'flamenco',
      'pato bebé',
      'canario',
      'gorrión',
      'golondrina',
      'pájaro carpintero',
      'petirrojo',
      'pájaro azul',
      'ganso',
      'avestruz bebé',
      'faisán bebé',
      'pavo real bebé',
      'pez payaso',
      'pez globo',
      'pez espada',
      'estrella de mar',
      'medusa pequeña',
      'langostino',
      'langosta pequeña',
      'ostra',
      'calamar pequeño',
      'sepia',
      'carpa',
      'salmón',
      'atún',
      'sardina',
      'trucha',
      'bacalao',
      'merluza',
      'boquerón',
      'anchoa',
      'centollo',
      'bogavante',
      'antílope',
      'gacela',
      'búfalo',
      'bisonte',
      'reno',
      'ciervo',
      'alce',
      'jabalí',
      'guepardo',
      'pantera',
      'leopardo',
      'hiena',
      'chacal',
      'topo',
      'comadreja',
      'hurón',
      'mofeta',
      'cabrita',
      'albaricoque',
      'arándano',
      'frambuesa',
      'mora',
      'pomelo',
      'lima',
      'papaya',
      'maracuyá',
      'higo',
      'dátil',
      'caqui',
      'nectarina',
      'membrillo',
      'aguacate',
      'clementina',
      'chirimoya',
      'grosella',
      'lichi',
      'espárrago',
      'coliflor',
      'alcachofa',
      'apio',
      'puerro',
      'remolacha',
      'nabo',
      'calabacín',
      'repollo',
      'col',
      'acelga',
      'espinaca',
      'judía verde',
      'lenteja',
      'garbanzo',
      'alubia',
      'soja',
      'haba',
      'batata',
      'boniato',
      'yuca',
      'rábano rojo',
      'mazorca',
      'perejil',
      'menta',
      'albahaca',
      'orégano',
      'canela',
      'sal',
      'azúcar',
      'harina',
      'aceite',
      'vinagre',
      'mayonesa',
      'kétchup',
      'mostaza',
      'jamón',
      'pollo',
      'carne',
      'filete',
      'albóndiga',
      'croqueta',
      'tortilla',
      'paella',
      'lasaña',
      'macarrones',
      'ravioli',
      'fideos',
      'puré',
      'caldo',
      'gazpacho',
      'empanada',
      'quesadilla',
      'burrito',
      'nachos',
      'palomita',
      'churro',
      'bizcocho',
      'cupcake',
      'brownie',
      'gofre',
      'tortita',
      'crepe',
      'flan de huevo',
      'gelatina',
      'natillas',
      'pudin',
      'merengue',
      'turrón',
      'mazapán',
      'chicle',
      'gominola',
      'bombón',
      'cacahuete',
      'almendra',
      'nuez',
      'avellana',
      'pistacho',
      'castaña',
      'semilla',
      'cereales',
      'avena',
      'salero',
      'azucarero',
      'panera',
      'servilleta',
      'mantel',
      'botella',
      'lata',
      'cartón de leche',
      'brik',
      'copa',
      'cuenco',
      'bol',
      'bandeja',
      'tabla de cortar',
      'rallador',
      'abrelatas',
      'sacacorchos',
      'exprimidor',
      'espátula',
      'pinzas',
      'cucharón',
      'embudo',
      'mortero',
      'delantal de cocina',
      'manopla de horno',
      'escurreplatos',
      'lavavajillas',
      'congelador',
      'campana extractora',
      'freidora',
      'cafetera italiana',
      'hervidor',
      'termo',
      'jarra medidora',
      'escobilla',
      'recogedor',
      'plumero',
      'cesta',
      'papel higiénico',
      'papel de cocina',
      'detergente',
      'suavizante',
      'pinza de ropa',
      'tendedero',
      'cesto de ropa',
      'secadora',
      'tabla de planchar',
      'perchero',
      'mesilla',
      'escritorio',
      'taburete',
      'banco',
      'cómoda',
      'vitrina',
      'cuna',
      'litera',
      'colchón',
      'sábana',
      'edredón',
      'cojín',
      'felpudo',
      'persiana',
      'macetero',
      'jarrón',
      'florero',
      'cenicero',
      'despertador digital',
      'mando a distancia',
      'ratón de ordenador',
      'impresora',
      'cargador',
      'cable',
      'memoria USB',
      'tableta',
      'portátil',
      'videoconsola',
      'móvil',
      'router',
      'micrófono',
      'webcam',
      'ventilador',
      'radiador',
      'aire acondicionado',
      'estufa',
      'chimenea',
      'termostato',
      'timbre',
      'interruptor',
      'caja de herramientas',
      'cinta adhesiva',
      'cuerda',
      'cadena',
      'gancho',
      'imperdible',
      'aguja',
      'hilo',
      'botón',
      'cremallera',
      'cordón',
      'pañuelo',
      'chaleco',
      'blusa',
      'polo',
      'top',
      'shorts',
      'vaqueros',
      'chándal',
      'uniforme',
      'traje',
      'esmoquin',
      'zuecos',
      'tacones',
      'bota de agua',
      'zapatilla de casa',
      'pantufla',
      'visera',
      'boina',
      'casco de moto',
      'gorro de lana',
      'diadema',
      'lazo',
      'corbata de lazo',
      'pajarita',
      'reloj de pulsera',
      'gafas de sol',
      'monedero',
      'maleta',
      'riñonera',
      'parka',
      'gabardina',
      'impermeable',
      'albornoz',
      'zapatilla de ballet',
      'mano abierta',
      'puño',
      'pulgar',
      'índice',
      'meñique',
      'antebrazo',
      'tobillo',
      'muslo',
      'gemelo',
      'pecho',
      'ombligo',
      'barbilla',
      'mejilla',
      'frente',
      'bigote',
      'barba',
      'coleta',
      'trenza',
      'rizo',
      'peca',
      'lágrima',
      'sonrisa',
      'huella',
      'sombra',
      'amanecer',
      'atardecer',
      'cielo',
      'tormenta',
      'niebla',
      'granizo',
      'hielo',
      'charco',
      'ola',
      'cascada',
      'arroyo',
      'estanque',
      'acantilado',
      'cueva',
      'valle',
      'colina',
      'pradera',
      'campo',
      'jardín',
      'huerto',
      'selva',
      'jungla',
      'sabana',
      'pantano',
      'glaciar',
      'iceberg',
      'isla tropical',
      'costa',
      'bahía',
      'golfo',
      'sendero',
      'camino',
      'carretera',
      'fruto',
      'arbusto',
      'enredadera',
      'bambú',
      'helecho',
      'musgo',
      'trébol',
      'amapola',
      'lavanda',
      'orquídea',
      'clavel',
      'lirio',
      'violeta',
      'diente de león',
      'bellota',
      'piña de pino',
      'coche de policía',
      'coche de bomberos',
      'coche de carreras',
      'cochecito de bebé',
      'carrito de compra',
      'patinete eléctrico',
      'bicicleta de montaña',
      'moto de campo',
      'scooter',
      'camión de bomberos',
      'camión de basura',
      'camión cisterna',
      'camión de helados',
      'autocar',
      'vagón',
      'locomotora pequeña',
      'ferry',
      'lancha',
      'bote',
      'barca',
      'piragua',
      'moto acuática',
      'avioneta',
      'avión de papel',
      'telecabina',
      'teleférico pequeño',
      'funicular',
      'carretilla',
      'carretilla elevadora',
      'excavadora',
      'apisonadora',
      'hormigonera',
      'bulldozer',
      'cosechadora',
      'patín',
      'patines de ruedas',
      'balón de fútbol',
      'balón de baloncesto',
      'balón de rugby',
      'balón de playa',
      'raqueta de tenis',
      'raqueta de pádel',
      'palo de hockey',
      'bate de béisbol',
      'guante de boxeo',
      'comba de saltar',
      'aro',
      'frisbi',
      'boomerang',
      'canasta de baloncesto',
      'portería pequeña',
      'red',
      'cono',
      'podio',
      'medalla de oro',
      'trofeo pequeño',
      'rompecabezas',
      'bloques de construcción',
      'cubo de Rubik',
      'muñeco',
      'muñeco de nieve',
      'caballo de juguete',
      'coche de juguete',
      'tren de juguete',
    ];

    const List<String> medio = [
      'camaleón',
      'iguana',
      'medusa',
      'caballito de mar',
      'erizo de mar',
      'langosta',
      'gamba',
      'almeja',
      'mejillón',
      'calamar',
      'morsa',
      'nutria',
      'castor',
      'mapache',
      'perezoso',
      'armadillo',
      'puercoespín',
      'ornitorrinco',
      'suricata',
      'lémur',
      'tucán',
      'colibrí',
      'pelícano',
      'cuervo',
      'urraca',
      'gaviota',
      'buitre',
      'cóndor',
      'halcón',
      'garza',
      'cigüeña',
      'pavo real',
      'faisán',
      'codorniz',
      'avestruz',
      'escorpión',
      'libélula',
      'saltamontes',
      'mantis',
      'luciérnaga',
      'ciempiés',
      'rinoceronte blanco',
      'gorila',
      'chimpancé',
      'orangután',
      'león marino',
      'narval',
      'orca',
      'raya',
      'anguila',
      'piraña',
      'dinosaurio',
      'tiranosaurio',
      'triceratops',
      'estegosaurio',
      'diplodocus',
      'pterodáctilo',
      'velociraptor',
      'mamut',
      'tigre dientes de sable',
      'locomotora',
      'tranvía',
      'teleférico',
      'globo aerostático',
      'dirigible',
      'planeador',
      'ala delta',
      'parapente',
      'hidroavión',
      'catamarán',
      'yate',
      'crucero',
      'portaaviones',
      'remolcador',
      'góndola',
      'kayak',
      'moto de agua',
      'quad',
      'karting',
      'grúa torre',
      'bombero',
      'policía',
      'médico',
      'enfermera',
      'profesor',
      'cocinero',
      'camarero',
      'panadero',
      'carnicero',
      'cartero',
      'jardinero',
      'mecánico',
      'fontanero',
      'electricista',
      'carpintero',
      'albañil',
      'peluquero',
      'dentista',
      'veterinario',
      'astronauta',
      'piloto',
      'azafata',
      'marinero',
      'capitán',
      'buzo',
      'soldado',
      'caballero',
      'pirata',
      'vaquero',
      'mago',
      'payaso',
      'malabarista',
      'domador',
      'bailarina',
      'torero',
      'árbitro',
      'científico',
      'arqueólogo',
      'escultor',
      'fotógrafo',
      'juez',
      'abogado',
      'chef',
      'peón',
      'rascacielos',
      'pagoda',
      'mezquita',
      'catedral',
      'coliseo',
      'pirámide',
      'esfinge',
      'acueducto',
      'noria',
      'montaña rusa',
      'tiovivo',
      'estadio',
      'piscina',
      'gimnasio',
      'biblioteca',
      'museo',
      'teatro',
      'cine',
      'circo',
      'acuario',
      'supermercado',
      'farmacia',
      'gasolinera',
      'aeropuerto',
      'estación',
      'puerto',
      'mercado',
      'fuente',
      'faro costero',
      'invernadero',
      'granero',
      'pozo',
      'colmena',
      'gallinero',
      'molino de viento',
      'raqueta',
      'portería',
      'canasta',
      'bate',
      'guante de béisbol',
      'palo de golf',
      'pesas',
      'mancuerna',
      'comba',
      'patines',
      'tabla de surf',
      'tabla de snow',
      'esquí',
      'trineo',
      'dardos',
      'billar',
      'bolos',
      'ping pong',
      'ajedrez',
      'rey',
      'reina',
      'alfil',
      'casco de ciclista',
      'silbato',
      'medalla',
      'trofeo',
      'portería de fútbol',
      'violín',
      'violonchelo',
      'contrabajo',
      'arpa',
      'acordeón',
      'saxofón',
      'clarinete',
      'oboe',
      'trombón',
      'tuba',
      'batería',
      'bongos',
      'armónica',
      'ukelele',
      'banjo',
      'mandolina',
      'órgano',
      'gaita',
      'castañuelas',
      'xilófono',
      'platillos',
      'telescopio',
      'microscopio',
      'satélite',
      'estación espacial',
      'traje espacial',
      'meteorito',
      'galaxia',
      'constelación',
      'platillo volante',
      'extraterrestre',
      'marciano',
      'robot gigante',
      'androide',
      'dron',
      'nave espacial',
      'astronave',
      'dragón',
      'unicornio',
      'sirena',
      'hada',
      'duende',
      'gnomo',
      'elfo',
      'enano',
      'ogro',
      'troll',
      'gigante',
      'minotauro',
      'centauro',
      'fénix',
      'cíclope',
      'momia',
      'vampiro',
      'fantasma',
      'zombi',
      'bruja',
      'hombre lobo',
      'calabaza de Halloween',
      'telaraña',
      'espantapájaros',
      'catalejo',
      'cofre del tesoro',
      'bandera pirata',
      'garfio',
      'pata de palo',
      'pergamino',
      'pluma de escribir',
      'mapa antiguo',
      'paracaídas',
      'salvavidas',
      'tienda de campaña',
      'saco de dormir',
      'hoguera',
      'cantimplora',
      'navaja suiza',
      'hacha',
      'brújula de mano',
      'probeta',
      'matraz',
      'tubo de ensayo',
      'balanza',
      'lupa',
      'imán',
      'termómetro',
      'jeringa',
      'estetoscopio',
      'venda',
      'muleta',
      'silla de ruedas',
      'máquina de escribir',
      'tocadiscos',
      'proyector',
      'prismáticos',
      'reloj de cuco',
      'reloj de sol',
      'semáforo',
      'farola',
      'buzón',
      'cabina de teléfono',
      'banco de parque',
      'estatua',
      'papelera',
      'boca de riego',
      'señal de stop',
      'paso de cebra',
      'túnel',
      'rotonda',
      'axolote',
      'tapir',
      'okapi',
      'yak',
      'dromedario',
      'llama',
      'alpaca',
      'ñu',
      'impala',
      'caribú',
      'muflón',
      'ibex',
      'pantera negra',
      'jaguar',
      'lince',
      'ocelote',
      'serval',
      'caracal',
      'coyote',
      'dingo',
      'tejón',
      'glotón',
      'mangosta',
      'capibara',
      'chinchilla',
      'marmota',
      'liebre',
      'antílope saiga',
      'wombat',
      'equidna',
      'pangolín',
      'oso hormiguero',
      'oso polar',
      'oso pardo',
      'oso negro',
      'foca leopardo',
      'elefante marino',
      'manatí',
      'dugongo',
      'beluga',
      'marsopa',
      'cachalote',
      'tiburón martillo',
      'tiburón ballena',
      'mantarraya',
      'pez sierra',
      'pez luna',
      'pez león',
      'morena',
      'barracuda',
      'caballa',
      'mero',
      'rape',
      'pez ángel',
      'anémona',
      'coral',
      'esponja marina',
      'nautilo',
      'cangrejo ermitaño',
      'cangrejo violinista',
      'langosta espinosa',
      'caracola',
      'babosa',
      'sanguijuela',
      'lombriz',
      'milpiés',
      'tarántula',
      'avispa',
      'abejorro',
      'escarabajo',
      'escarabajo rinoceronte',
      'escarabajo pelotero',
      'grillo',
      'cigarra',
      'polilla',
      'mosquito',
      'chinche',
      'termita',
      'pulga',
      'garrapata',
      'mariposa monarca',
      'mariposa nocturna',
      'mantis religiosa',
      'libélula azul',
      'mosca de la fruta',
      'escorpión emperador',
      'águila real',
      'águila calva',
      'búho nival',
      'lechuza',
      'halcón peregrino',
      'milano',
      'cernícalo',
      'quebrantahuesos',
      'frailecillo',
      'albatros',
      'cormorán',
      'martín pescador',
      'tucán toco',
      'cacatúa',
      'periquito',
      'flamenco rosa',
      'grulla',
      'ibis',
      'espátula rosada',
      'pingüino emperador',
      'pingüino rey',
      'cisne negro',
      'pájaro secretario',
      'casuario',
      'kiwi ave',
      'emú',
      'ñandú',
      'ave del paraíso',
      'quetzal',
      'somormujo',
      'focha',
      'ánade',
      'avefría',
      'petirrojo europeo',
      'dragón de Komodo',
      'cobra',
      'pitón',
      'boa',
      'serpiente de cascabel',
      'mamba negra',
      'víbora',
      'caimán',
      'gavial',
      'tortuga marina',
      'tortuga gigante',
      'galápago',
      'camaleón pantera',
      'gecko leopardo',
      'salamandra gigante',
      'tritón',
      'rana dardo',
      'rana toro',
      'sapo de caña',
      'ajolote',
      'velociraptor emplumado',
      'braquiosaurio',
      'ankylosaurio',
      'parasaurolophus',
      'spinosaurus',
      'allosaurus',
      'iguanodon',
      'pachycephalosaurus',
      'mosasaurio',
      'plesiosaurio',
      'arqueópterix',
      'pterosaurio',
      'sable láser',
      'casco vikingo',
      'casco romano',
      'armadura',
      'cota de malla',
      'catapulta',
      'ballesta',
      'arco y flecha',
      'carcaj',
      'lanza',
      'tridente',
      'honda',
      'cañón',
      'catapulta medieval',
      'ariete',
      'torre de asedio',
      'puente levadizo',
      'muralla',
      'foso',
      'mazmorra',
      'calabozo',
      'trono',
      'cetro',
      'corona real',
      'estandarte',
      'escudo vikingo',
      'barco vikingo',
      'drakkar',
      'barco pirata',
      'galeón',
      'fragata',
      'carabela',
      'barco de vapor',
      'barco pesquero',
      'rompehielos',
      'buque portacontenedores',
      'petrolero',
      'submarino amarillo',
      'balsa',
      'hovercraft',
      'zepelín',
      'helicóptero de rescate',
      'helicóptero militar',
      'avión de combate',
      'avión comercial',
      'avión de carga',
      'biplano',
      'ultraligero',
      'cohete espacial',
      'módulo lunar',
      'rover lunar',
      'rover marciano',
      'cápsula espacial',
      'sonda espacial',
      'observatorio',
      'radiotelescopio',
      'planetario',
      'cometa espacial',
      'asteroide',
      'planeta con anillos',
      'Saturno',
      'Júpiter',
      'Marte',
      'Tierra',
      'Luna llena',
      'eclipse solar',
      'eclipse lunar',
      'cráter',
      'supernova',
      'nebulosa',
      'agujero de gusano',
      'constelación de Orión',
      'Osa Mayor',
      'astronauta flotando',
      'casco espacial',
      'mochila propulsora',
      'robot explorador',
      'brazo robótico',
      'impresora 3D',
      'brazo mecánico',
      'engranajes',
      'cadena de montaje',
      'cinta transportadora',
      'grúa portuaria',
      'excavadora de ruedas',
      'retroexcavadora',
      'motoniveladora',
      'apisonadora de carretera',
      'camión volquete',
      'camión hormigonera',
      'camión grúa',
      'camión tráiler',
      'camión frigorífico',
      'camión cisterna de combustible',
      'autocaravana',
      'limusina',
      'coche descapotable',
      'coche clásico',
      'coche eléctrico',
      'coche de Fórmula 1',
      'monoplaza',
      'sidecar',
      'moto de motocross',
      'moto de nieve',
      'moto con sidecar',
      'bicicleta tándem',
      'bicicleta BMX',
      'bicicleta de carreras',
      'monociclo',
      'segway',
      'patinete de tres ruedas',
      'tractor con remolque',
      'carro de caballos',
      'diligencia',
      'trineo de perros',
      'teleférico de montaña',
      'funicular de montaña',
      'tren bala',
      'tren de mercancías',
      'tren nocturno',
      'tren de vapor',
      'vagón restaurante',
      'metro subterráneo',
      'tranvía antiguo',
      'ferrocarril de cremallera',
      'puente colgante',
      'puente levadizo moderno',
      'puente de piedra',
      'puente de cuerda',
      'viaducto',
      'túnel ferroviario',
      'rotonda con fuente',
      'cruce de caminos',
      'pasarela',
      'embarcadero',
      'dique',
      'presa',
      'faro con acantilado',
      'torre de control',
      'hangar',
      'pista de aterrizaje',
      'terminal de aeropuerto',
    ];

    const List<String> dificil = [
      'amor',
      'amistad',
      'felicidad',
      'tristeza',
      'miedo',
      'sorpresa',
      'enfado',
      'envidia',
      'vergüenza',
      'aburrimiento',
      'curiosidad',
      'esperanza',
      'suerte',
      'paz',
      'justicia',
      'mentira',
      'verdad',
      'secreto',
      'sueño',
      'pesadilla',
      'idea',
      'tiempo',
      'silencio',
      'frío',
      'calor',
      'velocidad',
      'gravedad',
      'equilibrio',
      'energía',
      'electricidad',
      'imaginación',
      'correr',
      'saltar',
      'nadar',
      'volar',
      'bailar',
      'cantar',
      'reír',
      'llorar',
      'dormir',
      'soñar',
      'pensar',
      'cocinar',
      'pintar',
      'pescar',
      'escalar',
      'bucear',
      'patinar',
      'esquiar',
      'remar',
      'boxear',
      'abrazar',
      'besar',
      'aplaudir',
      'estornudar',
      'bostezar',
      'susurrar',
      'gritar',
      'empujar',
      'cavar',
      'regar',
      'plantar',
      'barrer',
      'coser',
      'tejer',
      'tropezar',
      'resbalar',
      'esconderse',
      'perseguir',
      'enamorarse',
      'despedirse',
      'eclipse',
      'aurora boreal',
      'espejismo',
      'tornado',
      'huracán',
      'tsunami',
      'terremoto',
      'avalancha',
      'inundación',
      'sequía',
      'metamorfosis',
      'fotosíntesis',
      'ciclo del agua',
      'sistema solar',
      'átomo',
      'molécula',
      'célula',
      'neurona',
      'vía láctea',
      'agujero negro',
      'gravedad cero',
      'reacción en cadena',
      'efecto dominó',
      'movimiento perpetuo',
      'ilusión óptica',
      'laberinto',
      'gato con botas',
      'Caperucita',
      'lobo feroz',
      'tres cerditos',
      'patito feo',
      'Cenicienta',
      'Pinocho',
      'Aladino',
      'genio de la lámpara',
      'alfombra voladora',
      'árbol de Navidad',
      'Papá Noel',
      'Reyes Magos',
      'Cupido',
      'calavera mexicana',
      'torre Eiffel',
      'estatua de la Libertad',
      'Big Ben',
      'Taj Mahal',
      'muralla china',
      'torre de Pisa',
      'Cristo Redentor',
      'reloj derretido',
      'Gioconda',
      'globo ocular',
      'corazón anatómico',
      'pulmones',
      'estómago',
      'hígado',
      'riñón',
      'columna vertebral',
      'cráneo',
      'costillas',
      'sistema nervioso',
      'ADN',
      'copo de nieve',
      'cristal de hielo',
      'estalactita',
      'estalagmita',
      'geoda',
      'fósil',
      'duna',
      'oasis',
      'panal de abeja',
      'hormiguero',
      'madriguera',
      'nido',
      'crisálida',
      'telaraña con rocío',
      'tela de araña',
      'engranaje',
      'palanca',
      'polea',
      'rueda dentada',
      'muelle',
      'bisagra',
      'manivela',
      'reloj de cuco por dentro',
      'dominó cayendo',
      'castillo de naipes',
      'péndulo',
      'mariposas en el estómago',
      'pelos de punta',
      'estar en las nubes',
      'tirar la toalla',
      'dar en el clavo',
      'pan comido',
      'costar un ojo de la cara',
      'tomar el pelo',
      'hacer la pelota',
      'buscar una aguja en un pajar',
      'meter la pata',
      'dormir como un tronco',
      'llover a cántaros',
      'más vale pájaro en mano',
      'perro ladrador poco mordedor',
      'quien madruga Dios le ayuda',
      'a caballo regalado no le mires el diente',
      'ojo por ojo',
      'gota que colma el vaso',
      'nudo en la garganta',
      'lluvia de ideas',
      'doble sentido',
      'punto de vista',
      'faro en la tormenta',
      'barco en una botella',
      'mensaje en una botella',
      'naufragio',
      'isla desierta',
      'tesoro enterrado',
      'la equis marca el lugar',
      'perla en la ostra',
      'bola de cristal',
      'ovillo enredado',
      'huella dactilar',
      'código de barras',
      'código QR',
      'jeroglífico',
      'partitura',
      'clave de sol',
      'rosa de los vientos',
      'mapa estelar',
      'sombra chinesca',
      'reflejo en el agua',
      'cuenta atrás',
      'efecto mariposa',
      'reloj biológico',
      'equilibrista en la cuerda',
      'cama de clavos',
      'tragasables',
      'funambulista',
      'dominó',
      'diana',
      'encrucijada',
      'horizonte',
      'reciclaje',
      'cambio climático',
      'calentamiento global',
      'efecto invernadero',
      'lluvia ácida',
      'marea alta',
      'marea baja',
      'corriente marina',
      'remolino',
      'géiser',
      'erupción volcánica',
      'placa tectónica',
      'falla geológica',
      'onda sísmica',
      'lava',
      'magma',
      'cráter volcánico',
      'arrecife de coral',
      'cadena montañosa',
      'delta de un río',
      'meandro',
      'glaciar derritiéndose',
      'iceberg a la deriva',
      'tormenta eléctrica',
      'tormenta de arena',
      'tormenta de nieve',
      'relámpago',
      'trueno',
      'granizo gigante',
      'arcoíris doble',
      'halo solar',
      'luna roja',
      'luna de sangre',
      'lluvia de estrellas',
      'estrella fugaz',
      'cometa Halley',
      'rotación terrestre',
      'traslación terrestre',
      'fase lunar',
      'marea gravitatoria',
      'campo magnético',
      'polo norte',
      'polo sur',
      'ecuador terrestre',
      'huso horario',
      'mapa del mundo',
      'planisferio',
      'brújula rota',
      'norte magnético',
      'rosa de los vientos antigua',
      'escala de mapa',
      'pirámide alimenticia',
      'cadena alimentaria',
      'ecosistema',
      'hábitat',
      'especie en peligro',
      'selección natural',
      'camuflaje',
      'hibernación',
      'migración animal',
      'polinización',
      'germinación',
      'embrión',
      'virus',
      'bacteria',
      'anticuerpo',
      'vacuna',
      'circulación sanguínea',
      'latido del corazón',
      'reflejo',
      'impulso nervioso',
      'memoria a corto plazo',
      'memoria a largo plazo',
      'déjà vu',
      'insomnio',
      'sonambulismo',
      'hipnosis',
      'meditación',
      'telepatía',
      'rompecabezas imposible',
      'acertijo',
      'código secreto',
      'mensaje cifrado',
      'clave secreta',
      'candado con combinación',
      'huella en la nieve',
      'pista falsa',
      'sospechoso',
      'detective siguiendo huellas',
      'escena del crimen',
      'ladrón escapando',
      'robo de banco',
      'fuga de prisión',
      'persecución policial',
      'juicio',
      'prisión',
      'libertad condicional',
      'cadena perpetua',
      'balanza de la justicia',
      'martillo de juez',
      'testigo',
      'jurado',
      'interrogatorio',
    ];

    switch (level.toLowerCase().trim()) {
      case 'facil':
      case 'fácil':
        return facil;
      case 'dificil':
      case 'difícil':
        return dificil;
      case 'medio':
      default:
        return medio;
    }
  }

// MODIFY CODE ONLY ABOVE THIS LINE
}
