import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/auth/firebase_auth/auth_util.dart';

List<String> wordsForLevel(String level) {
  // ==========================================================================
//  wordsForLevel  —  banco de palabras por nivel (942, con tildes)
//  Declara en la UI:  argumento  level (String)  ·  Return  List<String>
//  y pega SOLO este cuerpo dentro de la función.
// ==========================================================================
  const facil = [
    'gato',
    'perro',
    'pez',
    'pájaro',
    'ratón',
    'vaca',
    'caballo',
    'cerdo',
    'oveja',
    'pato',
    'gallina',
    'conejo',
    'león',
    'tigre',
    'elefante',
    'mono',
    'oso',
    'jirafa',
    'cebra',
    'hipopótamo',
    'rinoceronte',
    'camello',
    'canguro',
    'koala',
    'panda',
    'lobo',
    'zorro',
    'ardilla',
    'erizo',
    'tortuga',
    'rana',
    'serpiente',
    'cocodrilo',
    'lagarto',
    'caracol',
    'araña',
    'abeja',
    'mariposa',
    'hormiga',
    'mosca',
    'gusano',
    'oruga',
    'pulpo',
    'cangrejo',
    'delfín',
    'ballena',
    'tiburón',
    'foca',
    'pingüino',
    'loro',
    'búho',
    'águila',
    'paloma',
    'cisne',
    'pavo',
    'gallo',
    'pollito',
    'cabra',
    'burro',
    'toro',
    'murciélago',
    'caballito',
    'manzana',
    'pera',
    'plátano',
    'naranja',
    'limón',
    'fresa',
    'cereza',
    'uva',
    'sandía',
    'melón',
    'piña',
    'kiwi',
    'mango',
    'coco',
    'melocotón',
    'ciruela',
    'mandarina',
    'granada',
    'tomate',
    'zanahoria',
    'patata',
    'cebolla',
    'pimiento',
    'lechuga',
    'pepino',
    'calabaza',
    'maíz',
    'brócoli',
    'champiñón',
    'ajo',
    'guisante',
    'aceituna',
    'berenjena',
    'rábano',
    'pan',
    'queso',
    'huevo',
    'leche',
    'mantequilla',
    'pizza',
    'hamburguesa',
    'perrito',
    'sándwich',
    'taco',
    'tostada',
    'galleta',
    'pastel',
    'tarta',
    'helado',
    'chocolate',
    'caramelo',
    'piruleta',
    'donut',
    'cruasán',
    'magdalena',
    'bocadillo',
    'sopa',
    'ensalada',
    'arroz',
    'pasta',
    'espagueti',
    'salchicha',
    'flan',
    'yogur',
    'miel',
    'mermelada',
    'palomitas',
    'patatas',
    'café',
    'té',
    'zumo',
    'agua',
    'refresco',
    'batido',
    'limonada',
    'silla',
    'mesa',
    'cama',
    'sofá',
    'sillón',
    'lámpara',
    'reloj',
    'espejo',
    'cuadro',
    'estantería',
    'armario',
    'cajón',
    'puerta',
    'ventana',
    'llave',
    'candado',
    'escoba',
    'cubo',
    'fregona',
    'plancha',
    'aspiradora',
    'televisión',
    'radio',
    'teléfono',
    'ordenador',
    'teclado',
    'pantalla',
    'altavoz',
    'auriculares',
    'cámara',
    'bombilla',
    'enchufe',
    'pila',
    'linterna',
    'vela',
    'cerilla',
    'mechero',
    'alfombra',
    'cortina',
    'almohada',
    'manta',
    'percha',
    'paraguas',
    'abanico',
    'despertador',
    'calendario',
    'tenedor',
    'cuchillo',
    'cuchara',
    'plato',
    'vaso',
    'taza',
    'jarra',
    'sartén',
    'olla',
    'cazo',
    'colador',
    'rodillo',
    'batidora',
    'tostadora',
    'tetera',
    'cafetera',
    'nevera',
    'horno',
    'microondas',
    'lavadora',
    'grifo',
    'ducha',
    'bañera',
    'inodoro',
    'lavabo',
    'jabón',
    'champú',
    'toalla',
    'peine',
    'secador',
    'tijeras',
    'esponja',
    'cepillo',
    'camiseta',
    'pantalón',
    'vestido',
    'falda',
    'abrigo',
    'chaqueta',
    'jersey',
    'sudadera',
    'camisa',
    'corbata',
    'cinturón',
    'calcetines',
    'zapatos',
    'zapatillas',
    'botas',
    'sandalias',
    'chanclas',
    'gorra',
    'sombrero',
    'bufanda',
    'guantes',
    'gafas',
    'anillo',
    'collar',
    'pendientes',
    'pulsera',
    'mochila',
    'bolso',
    'cartera',
    'bañador',
    'pijama',
    'delantal',
    'casco',
    'bikini',
    'gorro',
    'cabeza',
    'cara',
    'ojo',
    'oreja',
    'nariz',
    'boca',
    'diente',
    'lengua',
    'labio',
    'ceja',
    'pestaña',
    'pelo',
    'cuello',
    'hombro',
    'brazo',
    'codo',
    'mano',
    'dedo',
    'uña',
    'pierna',
    'rodilla',
    'pie',
    'talón',
    'barriga',
    'espalda',
    'corazón',
    'cerebro',
    'hueso',
    'esqueleto',
    'sol',
    'luna',
    'estrella',
    'nube',
    'lluvia',
    'nieve',
    'rayo',
    'arcoíris',
    'viento',
    'fuego',
    'gota',
    'montaña',
    'volcán',
    'río',
    'lago',
    'mar',
    'playa',
    'isla',
    'desierto',
    'bosque',
    'árbol',
    'flor',
    'hoja',
    'rama',
    'raíz',
    'tronco',
    'césped',
    'hierba',
    'roca',
    'piedra',
    'arena',
    'concha',
    'cactus',
    'seta',
    'pino',
    'palmera',
    'girasol',
    'rosa',
    'tulipán',
    'margarita',
    'hongo',
    'coche',
    'moto',
    'bicicleta',
    'camión',
    'autobús',
    'tren',
    'avión',
    'barco',
    'helicóptero',
    'cohete',
    'globo',
    'patinete',
    'monopatín',
    'triciclo',
    'tractor',
    'grúa',
    'ambulancia',
    'taxi',
    'furgoneta',
    'caravana',
    'submarino',
    'canoa',
    'velero',
    'pelota',
    'cometa',
    'yoyó',
    'peonza',
    'canica',
    'muñeca',
    'peluche',
    'robot',
    'tambor',
    'trompeta',
    'guitarra',
    'piano',
    'flauta',
    'maracas',
    'pandereta',
    'dado',
    'carta',
    'puzle',
    'tobogán',
    'columpio',
    'balancín',
    'globos',
    'lápiz',
    'bolígrafo',
    'goma',
    'sacapuntas',
    'regla',
    'cuaderno',
    'libro',
    'pincel',
    'pintura',
    'rotulador',
    'pegamento',
    'grapadora',
    'clip',
    'carpeta',
    'folio',
    'libreta',
    'mapa',
    'pizarra',
    'tiza',
    'calculadora',
    'círculo',
    'cuadrado',
    'triángulo',
    'rectángulo',
    'rombo',
    'óvalo',
    'flecha',
    'cruz',
    'espiral',
    'punto',
    'línea',
    'casa',
    'tienda',
    'escuela',
    'iglesia',
    'castillo',
    'faro',
    'puente',
    'torre',
    'cabaña',
    'iglú',
    'granja',
    'establo',
    'molino',
    'hospital',
    'bandera',
    'corona',
    'espada',
    'escudo',
    'cofre',
    'brújula',
    'ancla',
    'pala',
    'rastrillo',
    'regadera',
    'maceta',
    'manguera',
    'martillo',
    'destornillador',
    'sierra',
    'clavo',
    'tornillo',
    'llave inglesa',
    'metro',
    'sombrilla',
    'hamaca',
    'flotador',
    'reloj de arena',
  ];
  const medio = [
    'camaleón',
    'iguana',
    'medusa',
    'caballito de mar',
    'erizo de mar',
    'langosta',
    'gamba',
    'almeja',
    'mejillón',
    'calamar',
    'morsa',
    'nutria',
    'castor',
    'mapache',
    'perezoso',
    'armadillo',
    'puercoespín',
    'ornitorrinco',
    'suricata',
    'lémur',
    'tucán',
    'colibrí',
    'pelícano',
    'cuervo',
    'urraca',
    'gaviota',
    'buitre',
    'cóndor',
    'halcón',
    'garza',
    'cigüeña',
    'pavo real',
    'faisán',
    'codorniz',
    'avestruz',
    'escorpión',
    'libélula',
    'saltamontes',
    'mantis',
    'luciérnaga',
    'ciempiés',
    'rinoceronte blanco',
    'gorila',
    'chimpancé',
    'orangután',
    'león marino',
    'narval',
    'orca',
    'raya',
    'anguila',
    'pirañа',
    'dinosaurio',
    'tiranosaurio',
    'triceratops',
    'estegosaurio',
    'diplodocus',
    'pterodáctilo',
    'velociraptor',
    'mamut',
    'tigre dientes de sable',
    'locomotora',
    'tranvía',
    'teleférico',
    'globo aerostático',
    'dirigible',
    'planeador',
    'ala delta',
    'parapente',
    'hidroavión',
    'catamarán',
    'yate',
    'crucero',
    'portaaviones',
    'remolcador',
    'góndola',
    'kayak',
    'moto de agua',
    'quad',
    'karting',
    'grúa torre',
    'bombero',
    'policía',
    'médico',
    'enfermera',
    'profesor',
    'cocinero',
    'camarero',
    'panadero',
    'carnicero',
    'cartero',
    'jardinero',
    'mecánico',
    'fontanero',
    'electricista',
    'carpintero',
    'albañil',
    'peluquero',
    'dentista',
    'veterinario',
    'astronauta',
    'piloto',
    'azafata',
    'marinero',
    'capitán',
    'buzo',
    'soldado',
    'caballero',
    'pirata',
    'vaquero',
    'mago',
    'payaso',
    'malabarista',
    'domador',
    'bailarina',
    'torero',
    'árbitro',
    'científico',
    'arqueólogo',
    'escultor',
    'fotógrafo',
    'juez',
    'abogado',
    'chef',
    'peón',
    'rascacielos',
    'pagoda',
    'mezquita',
    'catedral',
    'coliseo',
    'pirámide',
    'esfinge',
    'acueducto',
    'noria',
    'montaña rusa',
    'tiovivo',
    'estadio',
    'piscina',
    'gimnasio',
    'biblioteca',
    'museo',
    'teatro',
    'cine',
    'circo',
    'acuario',
    'supermercado',
    'farmacia',
    'gasolinera',
    'aeropuerto',
    'estación',
    'puerto',
    'mercado',
    'fuente',
    'faro costero',
    'invernadero',
    'granero',
    'pozo',
    'colmena',
    'gallinero',
    'molino de viento',
    'raqueta',
    'portería',
    'canasta',
    'bate',
    'guante de béisbol',
    'palo de golf',
    'pesas',
    'mancuerna',
    'comba',
    'patines',
    'tabla de surf',
    'tabla de snow',
    'esquí',
    'trineo',
    'dardos',
    'billar',
    'bolos',
    'ping pong',
    'ajedrez',
    'rey',
    'reina',
    'alfil',
    'casco de ciclista',
    'silbato',
    'medalla',
    'trofeo',
    'portería de fútbol',
    'violín',
    'violonchelo',
    'contrabajo',
    'arpa',
    'acordeón',
    'saxofón',
    'clarinete',
    'oboe',
    'trombón',
    'tuba',
    'batería',
    'bongos',
    'armónica',
    'ukelele',
    'banjo',
    'mandolina',
    'órgano',
    'gaita',
    'castañuelas',
    'xilófono',
    'platillos',
    'telescopio',
    'microscopio',
    'satélite',
    'estación espacial',
    'traje espacial',
    'meteorito',
    'galaxia',
    'constelación',
    'platillo volante',
    'extraterrestre',
    'marciano',
    'robot gigante',
    'androide',
    'dron',
    'nave espacial',
    'astronave',
    'dragón',
    'unicornio',
    'sirena',
    'hada',
    'duende',
    'gnomo',
    'elfo',
    'enano',
    'ogro',
    'troll',
    'gigante',
    'minotauro',
    'centauro',
    'fénix',
    'cíclope',
    'momia',
    'vampiro',
    'fantasma',
    'zombi',
    'bruja',
    'hombre lobo',
    'calabaza de Halloween',
    'telaraña',
    'espantapájaros',
    'catalejo',
    'cofre del tesoro',
    'bandera pirata',
    'garfio',
    'pata de palo',
    'pergamino',
    'pluma de escribir',
    'mapa antiguo',
    'paracaídas',
    'salvavidas',
    'tienda de campaña',
    'saco de dormir',
    'hoguera',
    'cantimplora',
    'navaja suiza',
    'hacha',
    'brújula de mano',
    'probeta',
    'matraz',
    'tubo de ensayo',
    'balanza',
    'lupa',
    'imán',
    'termómetro',
    'jeringa',
    'estetoscopio',
    'venda',
    'muleta',
    'silla de ruedas',
    'máquina de escribir',
    'tocadiscos',
    'proyector',
    'prismáticos',
    'reloj de cuco',
    'reloj de sol',
    'semáforo',
    'farola',
    'buzón',
    'cabina de teléfono',
    'banco de parque',
    'estatua',
    'papelera',
    'boca de riego',
    'señal de stop',
    'paso de cebra',
    'túnel',
    'rotonda',
  ];
  const dificil = [
    'amor',
    'amistad',
    'felicidad',
    'tristeza',
    'miedo',
    'sorpresa',
    'enfado',
    'envidia',
    'vergüenza',
    'aburrimiento',
    'curiosidad',
    'esperanza',
    'suerte',
    'paz',
    'libertad',
    'justicia',
    'mentira',
    'verdad',
    'secreto',
    'sueño',
    'pesadilla',
    'idea',
    'tiempo',
    'silencio',
    'frío',
    'calor',
    'velocidad',
    'gravedad',
    'equilibrio',
    'energía',
    'electricidad',
    'imaginación',
    'memoria',
    'correr',
    'saltar',
    'nadar',
    'volar',
    'bailar',
    'cantar',
    'reír',
    'llorar',
    'dormir',
    'soñar',
    'pensar',
    'cocinar',
    'pintar',
    'pescar',
    'escalar',
    'bucear',
    'patinar',
    'esquiar',
    'remar',
    'boxear',
    'abrazar',
    'besar',
    'aplaudir',
    'estornudar',
    'bostezar',
    'susurrar',
    'gritar',
    'empujar',
    'cavar',
    'regar',
    'plantar',
    'barrer',
    'coser',
    'tejer',
    'tropezar',
    'resbalar',
    'esconderse',
    'perseguir',
    'enamorarse',
    'despedirse',
    'eclipse',
    'aurora boreal',
    'espejismo',
    'tornado',
    'huracán',
    'tsunami',
    'terremoto',
    'avalancha',
    'inundación',
    'sequía',
    'metamorfosis',
    'fotosíntesis',
    'ciclo del agua',
    'sistema solar',
    'átomo',
    'molécula',
    'célula',
    'neurona',
    'vía láctea',
    'agujero negro',
    'gravedad cero',
    'reacción en cadena',
    'efecto dominó',
    'movimiento perpetuo',
    'ilusión óptica',
    'laberinto',
    'gato con botas',
    'Caperucita',
    'lobo feroz',
    'tres cerditos',
    'patito feo',
    'Cenicienta',
    'Pinocho',
    'Aladino',
    'genio de la lámpara',
    'alfombra voladora',
    'árbol de Navidad',
    'Papá Noel',
    'Reyes Magos',
    'Cupido',
    'calavera mexicana',
    'torre Eiffel',
    'estatua de la Libertad',
    'Big Ben',
    'Taj Mahal',
    'muralla china',
    'torre de Pisa',
    'Cristo Redentor',
    'reloj derretido',
    'Gioconda',
    'globo ocular',
    'corazón anatómico',
    'pulmones',
    'estómago',
    'hígado',
    'riñón',
    'columna vertebral',
    'cráneo',
    'costillas',
    'sistema nervioso',
    'ADN',
    'copo de nieve',
    'cristal de hielo',
    'estalactita',
    'estalagmita',
    'geoda',
    'fósil',
    'duna',
    'oasis',
    'panal de abeja',
    'hormiguero',
    'madriguera',
    'nido',
    'crisálida',
    'telaraña con rocío',
    'tela de araña',
    'engranaje',
    'palanca',
    'polea',
    'rueda dentada',
    'muelle',
    'bisagra',
    'manivela',
    'reloj de cuco por dentro',
    'dominó cayendo',
    'castillo de naipes',
    'péndulo',
    'mariposas en el estómago',
    'pelos de punta',
    'estar en las nubes',
    'tirar la toalla',
    'dar en el clavo',
    'pan comido',
    'costar un ojo de la cara',
    'tomar el pelo',
    'hacer la pelota',
    'buscar una aguja en un pajar',
    'meter la pata',
    'dormir como un tronco',
    'llover a cántaros',
    'más vale pájaro en mano',
    'perro ladrador poco mordedor',
    'quien madruga Dios le ayuda',
    'a caballo regalado no le mires el diente',
    'ojo por ojo',
    'gota que colma el vaso',
    'nudo en la garganta',
    'lluvia de ideas',
    'doble sentido',
    'punto de vista',
    'faro en la tormenta',
    'barco en una botella',
    'mensaje en una botella',
    'naufragio',
    'isla desierta',
    'tesoro enterrado',
    'la equis marca el lugar',
    'perla en la ostra',
    'bola de cristal',
    'ovillo enredado',
    'huella dactilar',
    'código de barras',
    'código QR',
    'jeroglífico',
    'partitura',
    'clave de sol',
    'rosa de los vientos',
    'mapa estelar',
    'sombra chinesca',
    'reflejo en el agua',
    'cuenta atrás',
    'efecto mariposa',
    'reloj biológico',
    'equilibrista en la cuerda',
    'cama de clavos',
    'tragasables',
    'funambulista',
    'dominó',
    'diana',
    'encrucijada',
    'horizonte',
  ];
  switch (level) {
    case 'medio':
      return medio;
    case 'dificil':
      return dificil;
    default:
      return facil;
  }
}
